### ISSUE TITLE
Can't cast spells in a Fabric server

### ISSUE THREAD

**Issue by andrewmvk** [RobertSkalko/Age-of-Exile#58] opened 2021-02-11 18:57 UTC
I cast one spell in the game and it doesn't work.
It is identified, cost mana but does not work at all, the spell dont do damage and the ender pearl (first spell you start) dont pops up.

**Comment by RobertSkalko** [comment] 2021-02-11 19:00
Remove immersive portals mod.

**Comment by andrewmvk** [comment] 2021-02-11 19:23
I dont Have immersive portals mods, this are the mods in the 1.16.3 server: (Fabric 0.11.1)

AdventureZ 1.1.3
Age of Exile 1.7.10
Auto Config 3.3.1
Battle Towers 3.3.2
BetterCaves 1.03
BetterEnd 0.5.2
BetterMineshafts 1.0
BetterNether 4.1.8
BYG 1.1.3
Cardinal Components 2.7.11
Carrier 1.3.1
Config 2-4.8.3
Crimson Moon 1.2.3
Croptopia 1.1.0
Curious Fabric 0.0.10
DragonLoot 1.0.4
Dungeons Of Exile 1.1.1
Eldritch Mobs 1.5.1
Extra Origins 1
Fabric API 0.25.0+build.415
Fabric Chunkpregen 0.3.3
Fabric Language Kotlin 1.4.21
FatxpOrbs 0.0.9
Flesh2Leather 1.0.2
Gravestones 1.6
Heartbond 1.0.0
IronChest 1.1.3
Leaf Decay 1.2.0
Library Of Exile 1.0.6
Lithium 0.6.3
MCDA 0.9.1
MCDW 2.4.7
Mess 1.0.0
Mobs Attempt Parkour 0.2.1
MoStructures 1.0.1
Origins 0.3.8
Patchouli 44
Pehkui 
Phosphor 0.7.0
Quartz Elevator 1.1.0
Repurposed Structures 1.7.4
Rings Of Ascension 1.0.7
RughlyEnoughItems 5.9.171
SimpleBackPack 1.0.38
Sodium 0.1.0
Trinkets 2.6.6
Wraith Waystones 1.0.9
Yungs API 1

**Comment by SattesKrokodil** [comment] 2021-02-11 19:26
Crimson mood doesn't work with sodium I think. Try to disable one of them and check again

**Comment by andrewmvk** [comment] 2021-02-11 20:03
I removed the mods that you said, nothing changes, i tested disabling one by one, it doesn't work in the sigleplayer or in the fabric server.
I deleted even the config of the mods.
In the server the pops up this:
[17:50:17 INFO]: [STDERR]: java.lang.ClassCastException: com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity cannot be cast to net.minecraft.class_1667
[17:50:17 INFO]: [STDERR]: 	at net.minecraft.class_1665.<init>(class_1665.java:87)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity.<init>(SimpleProjectileEntity.java:105)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.mmorpg.registers.common.ModEntities$$Lambda$3090/434852496.create(Unknown Source)
[17:50:17 INFO]: [STDERR]: 	at net.minecraft.class_1299.method_5883(class_1299.java:463)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.components.ProjectileCastHelper.cast(ProjectileCastHelper.java:56)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.components.actions.SummonProjectileAction.tryActivate(SummonProjectileAction.java:93)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.components.ComponentPart.tryActivate(ComponentPart.java:96)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell.lambda$onCast$0(AttachedSpell.java:23)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell$$Lambda$5721/950869234.accept(Unknown Source)
[17:50:17 INFO]: [STDERR]: 	at java.util.ArrayList.forEach(Unknown Source)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell.onCast(AttachedSpell.java:23)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.database.data.spells.components.Spell.cast(Spell.java:112)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.saveclasses.spells.SpellCastingData.tryCast(SpellCastingData.java:164)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.saveclasses.spells.SpellCastingData.onTimePass(SpellCastingData.java:114)
[17:50:17 INFO]: [STDERR]: 	at com.robertx22.age_of_exile.event_hooks.ontick.OnServerTick.onEndTick(OnServerTick.java:178)
[17:50:17 INFO]: [STDERR]: 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$null$2(ServerTickEvents.java:62)
[17:50:17 INFO]: [STDERR]: 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$2402/1113160155.onEndTick(Unknown Source)
[17:50:17 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$bap001$onEndTick(MinecraftServer.java:4250)
[17:50:17 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:850)
[17:50:17 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
[17:50:17 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
[17:50:17 INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer$$Lambda$5013/1641231494.run(Unknown Source)
[17:50:17 INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)

**Comment by RobertSkalko** [comment] 2021-02-11 20:06
This might be because of new minecraft update actually

**Comment by andrewmvk** [comment] 2021-02-11 20:14
what do you think i need to do? i love this mod

**Comment by RobertSkalko** [comment] 2021-02-11 20:17
Wait for Mahj as he's currently the maintainer.

**Comment by andrewmvk** [comment] 2021-02-11 20:55
Now my server Crashed and the message of the crash was this:
java.lang.ClassCastException: com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity cannot be cast to net.minecraft.class_1667
	at net.minecraft.class_1665.<init>(class_1665.java:87)
	at com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity.<init>(SimpleProjectileEntity.java:105)
	at com.robertx22.age_of_exile.mmorpg.registers.common.ModEntities$$Lambda$3096/140242468.create(Unknown Source)
	at net.minecraft.class_1299.method_5883(class_1299.java:463)
	at com.robertx22.age_of_exile.database.data.spells.components.ProjectileCastHelper.cast(ProjectileCastHelper.java:56)
	at com.robertx22.age_of_exile.database.data.spells.components.actions.SummonProjectileAction.tryActivate(SummonProjectileAction.java:93)
	at com.robertx22.age_of_exile.database.data.spells.components.ComponentPart.tryActivate(ComponentPart.java:96)
	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell.lambda$onCast$0(AttachedSpell.java:23)
	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell$$Lambda$6123/1629816569.accept(Unknown Source)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell.onCast(AttachedSpell.java:23)
	at com.robertx22.age_of_exile.database.data.spells.components.Spell.cast(Spell.java:112)
	at com.robertx22.age_of_exile.mobs.ai.SpellAttackGoal.castInstantSpell(SpellAttackGoal.java:146)
	at com.robertx22.age_of_exile.mobs.ai.SpellAttackGoal.method_6268(SpellAttackGoal.java:135)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:649)
	at net.minecraft.class_1355.method_6275(class_1355.java:556)
	at net.minecraft.class_1308.method_6023(class_1308.java:736)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1547.method_6007(class_1547.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_3218.method_18762(class_3218.java:616)
	at net.minecraft.class_3218$$Lambda$5758/1611008937.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:406)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
	at net.minecraft.class_3176.method_3813(class_3176.java:303)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at net.minecraft.server.MinecraftServer$$Lambda$4985/1173011246.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1665.<init>(class_1665.java:87)
	at com.robertx22.age_of_exile.database.data.spells.entities.SimpleProjectileEntity.<init>(SimpleProjectileEntity.java:105)
	at com.robertx22.age_of_exile.mmorpg.registers.common.ModEntities$$Lambda$3096/140242468.create(Unknown Source)
	at net.minecraft.class_1299.method_5883(class_1299.java:463)
	at com.robertx22.age_of_exile.database.data.spells.components.ProjectileCastHelper.cast(ProjectileCastHelper.java:56)
	at com.robertx22.age_of_exile.database.data.spells.components.actions.SummonProjectileAction.tryActivate(SummonProjectileAction.java:93)
	at com.robertx22.age_of_exile.database.data.spells.components.ComponentPart.tryActivate(ComponentPart.java:96)
	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell.lambda$onCast$0(AttachedSpell.java:23)
	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell$$Lambda$6123/1629816569.accept(Unknown Source)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.robertx22.age_of_exile.database.data.spells.components.AttachedSpell.onCast(AttachedSpell.java:23)
	at com.robertx22.age_of_exile.database.data.spells.components.Spell.cast(Spell.java:112)
	at com.robertx22.age_of_exile.mobs.ai.SpellAttackGoal.castInstantSpell(SpellAttackGoal.java:146)
	at com.robertx22.age_of_exile.mobs.ai.SpellAttackGoal.method_6268(SpellAttackGoal.java:135)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:649)
	at net.minecraft.class_1355.method_6275(class_1355.java:556)
	at net.minecraft.class_1308.method_6023(class_1308.java:736)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1547.method_6007(class_1547.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_3218.method_18762(class_3218.java:616)
	at net.minecraft.class_3218$$Lambda$5758/1611008937.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: mmorpg:water_mage (com.robertx22.age_of_exile.mobs.mages.WaterMage)
	Entity ID: 1757
	Entity Name: entity.mmorpg.water_mage
	Entity's Exact location: -157.89, 49.00, 220.42
	Entity's Block location: World: (-158,49,220), Chunk: (at 2,3,12 in -10,13; contains blocks -160,0,208 to -145,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:406)

**Comment by andrewmvk** [comment] 2021-02-11 20:55
Its like the ''Water Mage'' crashed my game?

**Comment by andrewmvk** [comment] 2021-02-12 17:03
I find the problem, it is the ''MCWD'' mod, its was causing the bug, idk about the crash let me play and see if its gone.

**Comment by RobertSkalko** [comment] 2021-03-15 15:37
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:37 UTC
