### ISSUE TITLE
Vanilla Chicken spawning?

### ISSUE THREAD

**Issue by MechanosG** [RobertSkalko/Age-of-Exile#50] opened 2021-01-31 22:39 UTC
I'm not 100% certain AoE is doing this, so bear with me.

In singleplayer with AoE 1.7.8, I noticed sometimes enemy chickens spawn.  But on our test server, I haven't seen any of these enemy chickens spawn.  Instead, vanilla passive chickens seem to be spawning.  Since they don't despawn, they slowly accumulate, and now our game world is overran with chickens.  I don't actually know if AoE is responsible for this, and I'm not sure how to test it.  But chickens are the only mob being spawned like this, and I don't think the modpack has any other mods that force new passive mobs to spawn without chunk generation.

It's rather bizarre.  Do you have any advice on how I can confirm if AoE is doing this or not?

**Comment by RobertSkalko** [comment] 2021-03-15 15:38
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:38 UTC
