### ISSUE TITLE
[1.16.4] Client crash when putting on AoE boots- java.lang.NoSuchFieldError: armorModelProvider

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Age-of-Exile#42] opened 2020-11-19 18:11 UTC
https://gist.github.com/ProsperCraft/cbc9eeba54ea25c4a74a16abd7b88f94

Age-Of-Exile-1.16.3-1.7.6

**Comment by RobertSkalko** [comment] 2021-03-15 15:38
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:38 UTC
