### ISSUE TITLE
Fire Mage Entity Ticking causing the server to crash

### ISSUE THREAD

**Issue by faustojc** [RobertSkalko/Age-of-Exile#56] opened 2021-02-08 07:30 UTC
Spawning of Fire Mage entity makes my Aternos server to crash. I kept killing that specific entity to stop my server from crashing but still it keeps spawning naturally. 

Crash log:
[Crash Log.txt](https://github.com/RobertSkalko/Age-of-Exile/files/5941876/Crash.Log.txt)

**Comment by RobertSkalko** [comment] 2021-03-15 15:37
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:37 UTC
