### ISSUE TITLE
Crash on mob kill

### ISSUE THREAD

**Issue by Myp21** [RobertSkalko/Age-of-Exile#61] opened 2021-02-16 16:00 UTC
Hello. When im trying to kill mobs i get server crashed. Tried to use /kill command - same result
1.16.4
[crash-2021-02-16_18.28.59-server.txt](https://github.com/RobertSkalko/Age-of-Exile/files/5989869/crash-2021-02-16_18.28.59-server.txt)

**Comment by RobertSkalko** [comment] 2021-03-15 15:37
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:37 UTC
