### ISSUE TITLE
I'm having a crash with there mod in MC 1.16.3

### ISSUE THREAD

**Issue by VaderVirusExe** [RobertSkalko/Age-of-Exile#59] opened 2021-02-14 14:45 UTC
Idk why it's happening but it seems that it happens even when i have all the required libraries and mod updated. Maybe it's the fabric version or omething, i don't know
[crash report 14022021.txt](https://github.com/RobertSkalko/Age-of-Exile/files/5977913/crash.report.14022021.txt)

**Comment by RobertSkalko** [comment] 2021-03-15 15:37
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:37 UTC
