### ISSUE TITLE
Issue with using mod. (1.16.4)

### ISSUE THREAD

**Issue by Ozzysyn** [RobertSkalko/Age-of-Exile#46] opened 2020-12-20 03:07 UTC
Upon using all of the mods (and only those mods) that are necessary to use this mod:

- Age-Of-Exile-1.16.3-1.7.7
- Library-Of-Exile-1.16.3-1.0.6
- Patchouli-1.16-36-FABRIC
- fabric-api-0.25.4+1.16
- curios-fabric-0.0.10-1.16.3

A strange thing happens where it loads the game, doesn't crash, but instead just loads then unloads then loads again on the Mojang loading screen of minecraft.

**Comment by RobertSkalko** [comment] 2021-03-15 15:42
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:42 UTC
