### ISSUE TITLE
Axe weapons can't have axe enhants (or disable shields)

### ISSUE THREAD

**Issue by P03W** [RobertSkalko/Age-of-Exile#48] opened 2021-01-02 23:42 UTC
Because AoE axe weapons don't extend axe item, they

1. Cant receive axe enchants (only mending and unbreaking work)
2. Cant disable shields
3. Cant strip logs

3 isn't necessarily bad, but its something to be aware of if you decide to fix this

**Comment by RobertSkalko** [comment] 2021-03-15 15:38
Closing all bug related issues as I just pushed a big update. (many changes to the code)
If the issue is still there, please create a new issue and provide new log files.

The 1.8 update is currently BETA which means it's not ready for stable worlds. If you are playing multiplayer I suggest you wait for a release candidate.

**Closed by RobertSkalko** 2021-03-15 15:38 UTC
